### ISSUE TITLE
hello, help google music downloader

### ISSUE THREAD

**Issue by fabriguzden** [Athou/google-music-downloader#1]
How I use your project google music downloader, I followed all the instructions that appear in the script, but I failed
This is what I wrote in cmd: python google-music-downloader.py my email my password place of location album id
Press enter
And I get a message that I have to write: "usage: google-music-downloader <login> <password> <target directory> <album id>"
I do not understand that part between google-music-downloader and google-music-downloader.py

**Comment by Athou** [comment]
I don't know man, that should work. I changed the help, you indeed have to type `python google-music-downloader.py`.

**Comment by fabriguzden** [comment]
Ok, just tell me in detail how it is used and which version of python uses 2 or 3

**Comment by fabriguzden** [comment]
help
Traceback (most recent call last):
  File "google-music-downloader.py", line 24, in <module>
    dirPath = targetDir + "/" + dirName
TypeError: must be str, not bytes

**Comment by Athou** [comment]
I only tested the script using Python 2.7, I don't know if it works with Python 3.x

**Comment by Athou** [comment]
Can you update the script now  ? (you have to `pip install -r requirements` again)

**Comment by fabriguzden** [comment]
what python use 3 or 2

**Comment by Athou** [comment]
It should now work with both.

**Comment by fabriguzden** [comment]
thanks, working
